name: Playwright UI + API Tests

# Trigger workflow on push or PR
on:
  push:
    branches:
      - main
      - 'feature/*'
  pull_request:
    branches:
      - main
      - 'feature/*'

jobs:
  test:
    runs-on: ubuntu-latest
    strategy:
      matrix:
        node-version: [20]

    steps:
      # 1️⃣ Checkout the repository
      - name: Checkout code
        uses: actions/checkout@v3

      # 2️⃣ Setup Node.js
      - name: Setup Node.js
        uses: actions/setup-node@v3
        with:
          node-version: ${{ matrix.node-version }}

      # 3️⃣ Install dependencies
      - name: Install dependencies
        run: npm ci

      # 4️⃣ Install Playwright browsers
      - name: Install Playwright Browsers
        run: npx playwright install --with-deps

      # 5️⃣ Run all Playwright tests
      - name: Run UI + API tests
        run: npx playwright test --reporter=list

      # 6️⃣ Generate Allure report
      - name: Generate Allure Report
        run: |
          npx allure generate allure-results --clean -o allure-report || true

      # 7️⃣ Upload Allure report as artifact
      - name: Upload Allure Report
        uses: actions/upload-artifact@v4
        with:
          name: allure-report
          path: allure-report

      # 8️⃣ Optional: Upload screenshots/videos for failed tests
      - name: Upload Playwright Artifacts
        if: failure()
        uses: actions/upload-artifact@v4
        with:
          name: playwright-artifacts
          path: |
            playwright-report
            tests/ui/screenshots
            tests/ui/videos
